proyecto/proyecto/urls.py
from django.contrib import admin
from django.urls import include, path

from django.contrib.auth import views

urlpatterns = [
    path('servicios/', include('servicios.urls')),
    path('accounts/login/', views.LoginView.as_view(), name='login'),
    path('accounts/logout/', views.LogoutView.as_view(next_page='/servicios/'), name='logout'),
    path('admin/', admin.site.urls),
    
]

proyecto/servicios/urls.py
from django.urls import path

from . import views

app_name = 'servicios'
urlpatterns = [
    # ex: /servicios/
    path('', views.index, name='index'),
    # ex: /servicios/5/
    path('<int:servicio_id>/', views.detalle, name='detalle'),
    # ex: /servicios/nuevo_servicio
    path('nuevo/', views.nuevo_servicio, name='nuevo_servicio'),
    # ex: /servicios/3/editar
    path('<int:servicio_id>/editar/', views.editar_servicio, name='editar_servicio'),
    # ex: /servicios/3/eliminar
    path('<int:servicio_id>/eliminar/', views.eliminar_servicio, name='eliminar_servicio'),
    #
    path('<int:servicio_id>/finalizar/', views.finalizar_servicio, name='finalizar_servicio'),
    
    
    # ex: /servicios/tarea/5/
    path('tarea/<int:tarea_id>/', views.tarea, name='tarea'),
    # ex: /servicios/3/tarea/nueva
    path('<int:servicio_id>/tarea/nueva/', views.nueva_tarea, name='nueva_tarea'),
    # ex: /servicios/tarea/3/editar
    path('tarea/<int:tarea_id>/editar/', views.editar_tarea, name='editar_tarea'),
    #
    path('tarea/<int:tarea_id>/eliminar/', views.eliminar_tarea, name='eliminar_tarea'),
    #
    path('tarea/<int:tarea_id>/finalizar/', views.finalizar_tarea, name='finalizar_tarea'),
    
    # ex: /servicios/parte/5/
    path('parte/<int:parte_id>/', views.parte, name='parte'),
    # ex: /servicios/3/parte/nuevo
    path('<int:tarea_id>/parte/nuevo/', views.nuevo_parte, name='nuevo_parte'),
    # ex: /servicios/3/parte/jnuevo
    path('<int:tarea_id>/parte/jnuevo/', views.nuevo_parte_coord, name='nuevo_parte_coord'),
    # ex: /servicios/parte/3/editar
    path('parte/<int:parte_id>/editar/', views.editar_parte, name='editar_parte'),
    #
    path('parte/<int:parte_id>/eliminar/', views.eliminar_parte, name='eliminar_parte'),
    #
    path('parte/<int:parte_id>/aprobar/', views.aprobar_parte, name='aprobar_parte'),
    
    # ex: /servicios/cliente/2
    path('cliente/<int:cliente_id>/', views.cliente, name='cliente'),
    # ex: /servicios/clientes
    path('clientes/', views.clientes, name='clientes'),
    #  
    path('cliente/nuevo/', views.nuevo_cliente, name='nuevo_cliente'),
    # 
    path('cliente/<int:cliente_id>/editar/', views.editar_cliente, name='editar_cliente'),
    #
    path('cliente/<int:cliente_id>/eliminar/', views.eliminar_cliente, name='eliminar_cliente'),
    
    
    # ex: /servicios/empleado/4    
    path('empleado/<int:empleado_id>/', views.empleado, name='empleado'),
    #     
    path('empleado/<int:cuadrilla_id>/nuevo/', views.nuevo_empleado, name='nuevo_empleado'),
    #     
    path('empleado/<int:empleado_id>/editar', views.editar_empleado, name='editar_empleado'),
    #     
    path('empleado/<int:empleado_id>/eliminar', views.eliminar_empleado, name='eliminar_empleado'),
    
    # ex: /servicios/cuadrillas    
    path('cuadrillas/', views.cuadrillas, name='cuadrillas'),
    # ex: /servicios/cuadrilla/2
    path('cuadrilla/<int:cuadrilla_id>/', views.cuadrilla, name='cuadrilla'),
    #  
    path('cuadrilla/nueva/', views.nueva_cuadrilla, name='nueva_cuadrilla'),
    # 
    path('cuadrilla/<int:cuadrilla_id>/editar/', views.editar_cuadrilla, name='editar_cuadrilla'),
    #
    path('cuadrilla/<int:cuadrilla_id>/eliminar/', views.eliminar_cuadrilla, name='eliminar_cuadrilla'),
    #
    path('cuadrilla/<int:cuadrilla_id>/seleccionar_jefe/', views.seleccionar_jefe, name='seleccionar_jefe'),
    #
    path('cuadrilla/<int:cuadrilla_id>/seleccionar_jefe2/', views.seleccionar_jefe2, name='seleccionar_jefe2'),
    
        
]

proyecto/servicios/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Cliente(models.Model):
    nombre = models.CharField(max_length=100)
    direccion = models.CharField(max_length=100)
    telefono = models.CharField(max_length=15)
    descripcion = models.CharField(max_length=200)

    def __str__(self):
        return self.nombre


class Servicio(models.Model):
    ESTADOS = (
        ('Pendiente', 'Pendiente'),
        ('En curso', 'En curso'),
        ('Finalizado', 'Finalizado'),    
    )    
    cliente = models.ForeignKey(Cliente, on_delete=models.CASCADE)    
    fecha_solcitud = models.DateField('fecha de solicitud')
    fecha_inicio = models.DateField('fecha de inicio', blank=True, null=True)
    fecha_fin = models.DateField('fecha de fin', blank=True, null=True)
    descripcion = models.CharField(max_length=500)
    estado = models.CharField(max_length=12, choices=ESTADOS)
    

    def __str__(self):
        return self.descripcion


class Cuadrilla(models.Model):
    especialidad = models.CharField(max_length=100)
    vehiculo = models.CharField(max_length=50)
    def jefe(self):
        return self.empleadodecuadrilla_set.get(es_jefe=True)

    def __str__(self):
        return self.especialidad


class Tarea(models.Model):
    servicio = models.ForeignKey(Servicio, on_delete=models.CASCADE)    
    descripcion = models.CharField(max_length=200)
    ESTADOS = (
        ('Pendiente', 'Pendiente'),
        ('En curso', 'En curso'),
        ('Finalizado', 'Finalizado'),    
    )    
    estado = models.CharField(max_length=12, choices=ESTADOS)
    cuadrilla = models.ForeignKey(Cuadrilla, on_delete=models.SET_NULL, blank=True, null=True)

    def __str__(self):
        return self.descripcion


class EmpleadoDeCuadrilla(models.Model):
    legajo = models.IntegerField(default=0)
    cuil = models.CharField(max_length=13)
    cuadrilla = models.ForeignKey(Cuadrilla, on_delete=models.SET_NULL, blank=True, null=True)
    nombre = models.CharField(max_length=50)
    apellido = models.CharField(max_length=50)
    empleado_desde = models.DateField('empleado desde')
    fecha_nac = models.DateField('fecha de nacimiento')
    es_jefe = models.BooleanField('es jefe de cuadrilla', default=False)
    
    def __str__(self):
        return self.apellido


class ParteDeTrabajo(models.Model):
    fecha = models.DateField()
    tarea = models.ForeignKey(Tarea, on_delete=models.CASCADE)
    descripcion = models.CharField(max_length=200)
    aprobado_por = models.ForeignKey(User, on_delete=models.SET_NULL, blank=True, null=True)

    def __str__(self):
        return self.descripcion

proyecto/servicios/views.py
from django.shortcuts import get_object_or_404, render, redirect

from django.http import HttpResponse
from django.template import loader

from .models import Servicio, Cliente, EmpleadoDeCuadrilla, Cuadrilla, Tarea, ParteDeTrabajo

from django.http import Http404, HttpResponse, HttpResponseRedirect
from django.urls import reverse

from .forms import ServicioForm, TareaForm, ParteForm, ClienteForm, CuadrillaForm, EmpleadoForm

from django.contrib.auth.decorators import login_required

from django.contrib.auth.models import User, Group

from django.utils import timezone

from django.db.models import Q

@login_required
def index(request):
    lista_servicios = Servicio.objects.order_by('-fecha_solcitud')[:20]
    es_coordinador = es_miembro(request, 'coordinador')
    es_administrativo = es_miembro(request, 'administrativo')
    context = {'lista_servicios': lista_servicios, 'es_coordinador': es_coordinador, 'es_administrativo': es_administrativo, 'user': request.user}
    return render(request, 'servicios/index.html', context)

            
@login_required
def detalle(request, servicio_id):
    servicio = get_object_or_404(Servicio, pk=servicio_id)
    es_coordinador = es_miembro(request, 'coordinador')
    es_administrativo = es_miembro(request, 'administrativo')
    context = {'servicio': servicio, 'es_coordinador': es_coordinador, 'es_administrativo': es_administrativo}
    return render(request, 'servicios/detalle.html', context)

@login_required
def nuevo_servicio(request):
    if request.method == "POST":
        form = ServicioForm(request.POST)
        if form.is_valid():
            servicio = form.save(commit=False)
            servicio.save()
            return HttpResponseRedirect(reverse('servicios:detalle', args=(servicio.id,)))
    else:
        form = ServicioForm(initial={'fecha_solcitud': timezone.now(), 'fecha_inicio': timezone.now(), 'estado': 'Pendiente'})
    return render(request, 'servicios/editar_servicio.html', {'form': form})


@login_required    
def editar_servicio(request, servicio_id):
    servicio = get_object_or_404(Servicio, pk=servicio_id)
    if request.method == "POST":
        form = ServicioForm(request.POST, instance=servicio)
        if form.is_valid():
            servicio = form.save(commit=False)
            servicio.save()
            return HttpResponseRedirect(reverse('servicios:detalle', args=(servicio.id,)))
    else:
        form = ServicioForm(instance=servicio)
    return render(request, 'servicios/editar_servicio.html', {'form': form})


@login_required    
def eliminar_servicio(request, servicio_id):
    servicio = get_object_or_404(Servicio, pk=servicio_id)
    servicio.delete()
    return HttpResponseRedirect(reverse('servicios:index'))    


def finalizar_servicio(request, servicio_id):
    servicio = get_object_or_404(Servicio, pk=servicio_id)
    es_coordinador = es_miembro(request, 'coordinador')
    es_administrativo = es_miembro(request, 'administrativo')
    if servicio.tarea_set.filter(~Q(estado='Finalizado')).exists():
        return render(request, 'servicios/detalle.html', {
        'servicio': servicio,
        'error_message': 'No se puede finalizar servicio. Existe al menos una tarea sin finalizar.',
        'es_administrativo': es_administrativo,
        'es_coordinador': es_coordinador})
    else:
        servicio.estado = 'Finalizado'
        servicio.fecha_fin = timezone.now()
        servicio.save()
    return HttpResponseRedirect(reverse('servicios:detalle', args=(servicio.id,)))
    

@login_required        
def tarea(request, tarea_id):
    tarea = get_object_or_404(Tarea, pk=tarea_id)
    es_coordinador = es_miembro(request, 'coordinador')
    es_administrativo = es_miembro(request, 'administrativo')
    context = {'tarea': tarea, 'es_coordinador': es_coordinador, 'es_administrativo': es_administrativo}
    return render(request, 'servicios/tarea.html', context)

@login_required
def nueva_tarea(request, servicio_id):
    if request.method == "POST":
        form = TareaForm(request.POST)
        if form.is_valid():
            tarea = form.save(commit=False)            
            tarea.save()
            servicio = Servicio.objects.get(pk=servicio_id)
            servicio.estado = 'En curso'
            servicio.save()
            return HttpResponseRedirect(reverse('servicios:tarea', args=(tarea.id,)))
    else:
        form = TareaForm(initial={'servicio': servicio_id, 'estado': 'Pendiente'})
    return render(request, 'servicios/editar_tarea.html', {'form': form})

@login_required    
def editar_tarea(request, tarea_id):
    tarea = get_object_or_404(Tarea, pk=tarea_id)
    if request.method == "POST":
        form = TareaForm(request.POST, instance=tarea)
        if form.is_valid():
            tarea = form.save(commit=False)
            tarea.save()
            return HttpResponseRedirect(reverse('servicios:tarea', args=(tarea.id,)))
    else:
        form = TareaForm(instance=tarea)
    return render(request, 'servicios/editar_tarea.html', {'form': form})    

@login_required
def eliminar_tarea(request, tarea_id):
    tarea = get_object_or_404(Tarea, pk=tarea_id)
    servicio_id=tarea.servicio.id
    tarea.delete()
    return HttpResponseRedirect(reverse('servicios:detalle', args=(servicio_id,)))    

def finalizar_tarea(request, tarea_id):
    tarea = get_object_or_404(Tarea, pk=tarea_id)
    es_coordinador = es_miembro(request, 'coordinador')
    if tarea.partedetrabajo_set.filter(aprobado_por=None).exists():
        return render(request, 'servicios/tarea.html', {
        'tarea': tarea,
        'error_message': 'No se puede finalizar tarea. Existe al menos un parte sin aprobar.',
        'es_coordinador': es_coordinador})
    else:    
        tarea.estado = 'Finalizado'
        tarea.save()    
    return HttpResponseRedirect(reverse('servicios:tarea', args=(tarea.id,)))


@login_required
def parte(request, parte_id):
    parte = get_object_or_404(ParteDeTrabajo, pk=parte_id)
    return render(request, 'servicios/parte.html', {'parte': parte, 'es_coordinador': es_miembro(request, 'coordinador')})

@login_required
def nuevo_parte(request, tarea_id):
    if request.method == "POST":
        form = ParteForm(request.POST)
        if form.is_valid():
            parte = form.save(commit=False)
            parte.save()
            tarea = Tarea.objects.get(pk=tarea_id)
            tarea.estado = 'En curso'
            tarea.save()
            servicio = Servicio.objects.get(pk=tarea.servicio.id)
            servicio.estado = 'En curso'
            if servicio.fecha_inicio == None:
                servicio.fecha_inicio = parte.fecha
            servicio.save() 
            return HttpResponseRedirect(reverse('servicios:parte', args=(parte.id,)))
    else:
        form = ParteForm(initial={'tarea': tarea_id, 'fecha': timezone.now() })
    return render(request, 'servicios/editar_parte.html', {'form': form})


def nuevo_parte_coord(request, tarea_id):
    if request.method == "POST":
        form = ParteForm(request.POST)
        if form.is_valid():
            parte = form.save(commit=False)
            parte.aprobado_por = request.user
            parte.save()
            tarea = Tarea.objects.get(pk=tarea_id)
            tarea.estado = 'En curso'
            tarea.save()
            servicio = Servicio.objects.get(pk=tarea.servicio.id)
            servicio.estado = 'En curso'
            if servicio.fecha_inicio == None:
                servicio.fecha_inicio = parte.fecha
            servicio.save() 
            return HttpResponseRedirect(reverse('servicios:parte', args=(parte.id,)))
    else:
        form = ParteForm(initial={'tarea': tarea_id, 'fecha': timezone.now()})
    return render(request, 'servicios/editar_parte.html', {'form': form})

@login_required    
def editar_parte(request, parte_id):
    parte = get_object_or_404(ParteDeTrabajo, pk=parte_id)
    if request.method == "POST":
        form = ParteForm(request.POST, instance=parte)
        if form.is_valid():
            parte = form.save(commit=False)
            parte.save()
            return HttpResponseRedirect(reverse('servicios:parte', args=(parte.id,)))
    else:
        form = ParteForm(instance=parte)
    return render(request, 'servicios/editar_parte.html', {'form': form})    

@login_required
def eliminar_parte(request, parte_id):
    parte = get_object_or_404(ParteDeTrabajo, pk=parte_id)
    tarea_id=parte.tarea.id
    parte.delete()
    return HttpResponseRedirect(reverse('servicios:tarea', args=(tarea_id,)))    

def aprobar_parte(request, parte_id):
    parte = get_object_or_404(ParteDeTrabajo, pk=parte_id)
    parte.aprobado_por = request.user
    parte.save()
    return HttpResponseRedirect(reverse('servicios:parte', args=(parte_id,)))    


@login_required
def clientes(request):
    lista_clientes = Cliente.objects.order_by('-nombre')[:20]
    es_administrativo = es_miembro(request, 'administrativo')
    context = {'lista_clientes': lista_clientes, 'es_administrativo': es_administrativo}
    return render(request, 'servicios/clientes.html', context)

@login_required
def cliente(request, cliente_id):
    cliente = get_object_or_404(Cliente, pk=cliente_id)
    es_administrativo = es_miembro(request, 'administrativo')
    context = {'cliente': cliente, 'es_administrativo': es_administrativo}
    return render(request, 'servicios/cliente.html', context)

@login_required
def nuevo_cliente(request):
    if request.method == "POST":
        form = ClienteForm(request.POST)
        if form.is_valid():
            cliente = form.save(commit=False)            
            cliente.save()
            return HttpResponseRedirect(reverse('servicios:cliente', args=(cliente.id,)))
    else:
        form = ClienteForm()
    return render(request, 'servicios/editar_cliente.html', {'form': form})

@login_required    
def editar_cliente(request, cliente_id):
    cliente = get_object_or_404(Cliente, pk=cliente_id)
    if request.method == "POST":

proyecto/servicios/templates/servicios/cliente.html
{% extends 'servicios/base.html' %}

{% block main %}

    {% if cliente %}
        <h2>Cliente</h2>
               
        <table class="table">
            <tr>
                <th>Nombre</th>
                <th>Dirección</th>
                <th>Descripción</th>
                <th>Teléfono</th>
                </tr>
            
                <tr>
                    
                    <td>{{cliente.nombre}}</td>
                    <td>{{cliente.direccion}}</td>
                    <td>{{cliente.descripcion}}</td>
                    <td>{{cliente.telefono}}</td>
                    
                </tr>
            
            
        </table>
        
        <p>
        {% if es_administrativo %} 
            <a href="{% url 'servicios:editar_cliente' cliente.id %}"><button type="button" class="btn btn-primary">Editar Cliente</button></a>
            <a href="{% url 'servicios:eliminar_cliente' cliente.id %}"><button type="button" class="btn btn-primary">Eliminar Cliente</button></a>
        {% endif %}    
            <a href="{% url 'servicios:clientes' %}"><button type="button" class="btn btn-primary">Lista Clientes</button></a>
        </p>

    {% else %}
        <p>No existe cliente</p>
    {% endif %}
    

{% endblock %}

proyecto/servicios/templates/servicios/cuadrilla.html
{% extends 'servicios/base.html' %}

{% block main %}

<br>
<h3><b>Cuadrilla</b>: {{ cuadrilla.especialidad }}</h3>
<br>

<table class="table">
            <tr>
                <th>Vehículo</th>
                <th>Jefe</th>
            </tr>
            
            <tr>
                <td>{{cuadrilla.vehiculo}}</td>
                <td>
                {% if cuadrilla.jefe %}
                    <a href="{% url 'servicios:empleado' cuadrilla.jefe.id %}">{{cuadrilla.jefe.apellido}}</a>
                {% else %}
                    No se agregó jefe a cuadrilla
                {% endif %}
                </td>
            </tr>
            
        </table>
        
        <p>
        {% if es_administrativo %}
        <a href="{% url 'servicios:editar_cuadrilla' cuadrilla.id %}"><button type="button" class="btn btn-primary">Editar Cuadrilla</button></a>
        <a href="{% url 'servicios:eliminar_cuadrilla' cuadrilla.id %}"><button type="button" class="btn btn-primary">Eliminar Cuadrilla</button></a>
        {% endif %}
        <a href="{% url 'servicios:cuadrillas' %}"><button type="button" class="btn btn-primary">Volver a Cuadrillas</button></a></p>
        

{% if cuadrilla.empleadodecuadrilla_set.all %}

    <h4>Empleados:</h4>
            
        <table class="table">
            <tr>
                <th>Legajo</th>
                <th>Cuil</th>
                <th>Cuadrilla</th>
                <th>Nombre</th>
                <th>Apellido</th>
                <th>Fecha de nacimiento</th>                
                <th>Empleado desde</th>
                <th>Es jefe</th>
                </tr>
                
                {% for empleado in cuadrilla.empleadodecuadrilla_set.all %}
                
                <tr>
                    <td><a href="{% url 'servicios:empleado' empleado.id %}">{{empleado.legajo}}</a></td>
                    <td>{{empleado.cuil}}</td>
                    <td>{{empleado.cuadrilla}}</td>
                    <td>{{empleado.nombre}}</td>
                    <td>{{empleado.apellido}}</td>
                    <td>{{empleado.fecha_nac}}</td>
                    <td>{{empleado.empleado_desde}}</td>
                    {% if empleado.es_jefe %}
                    <td><i class="fa fa-check" aria-hidden="true"></i></td>
                    {% else %}
                    <td><i class="fa fa-times" aria-hidden="true"></i></td>
                    {% endif %}
                </tr>
                
                {% endfor %}            
            
        </table>
        
        
{% else %}
    <p>Cuadrilla no posee empleados</p>
{% endif %}

{% if es_administrativo %}
<p>
    <a href="{% url 'servicios:nuevo_empleado' cuadrilla.id %}"><button type="button" class="btn btn-primary">Agregar Empleado</button></a>
    <a href="{% url 'servicios:seleccionar_jefe' cuadrilla.id %}"><button type="button" class="btn btn-primary">Seleccionar Jefe</button></a>  
</p>
{% endif %}

{% endblock %}

proyecto/servicios/templates/servicios/detalle.html
{% extends 'servicios/base.html' %}

{% block main %}

<h3><b>Servicio</b>: {{ servicio.descripcion }}</h3>


{% if es_coordinador or es_administrativo %}
<div class="actions">
    <a href="{% url 'servicios:editar_servicio' servicio.id%}">
        <button type="button" class="btn btn-primary">Editar Servicio</button>
    </a>
    <a href="{% url 'servicios:eliminar_servicio' servicio.id%}">
        <button type="button" class="btn btn-primary">Eliminar Servicio</button>
    </a>
    {% if servicio.estado != 'Finalizado' %}
    <a href="{% url 'servicios:finalizar_servicio' servicio.id %}">
        <button type="button" class="btn btn-primary">Finalizar Servicio</button>
    </a>
    {% endif %}
    <a href="{% url 'servicios:nueva_tarea' servicio.id %}">
        <button type="button" class="btn btn-primary">Agregar Tarea</button>
    </a>
</div>
{% endif %}

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<div class="detail">
    <h5><b>Cliente:</b> {{ servicio.cliente }}</h5>
    <h5><b>Fecha de solicitud:</b> {{ servicio.fecha_solcitud }}</h5>
    <h5><b>Fecha de inicio:</b> {{ servicio.fecha_inicio|default_if_none:"Fecha no definida" }}</h5>
    <h5><b>Fecha de finalización:</b> {{ servicio.fecha_fin|default_if_none:"Fecha no definida" }}</h5>
    <h5><b>Estado:</b> {{ servicio.estado }}</h5>
</div>

{% if servicio.tarea_set.all %}

    <h4><b>Tareas:</b></h4>

        {% for tarea in servicio.tarea_set.all %}
            <h5><a href="{% url 'servicios:tarea' tarea.id %}">{{tarea.descripcion}}</a>: <i>{{tarea.estado}}</i></h5>

            {% if tarea.partedetrabajo_set.all %}
                <h5>Partes de trabajo</h5>
                <table class="table">
                    <tr>
                        <th>Descripción</th>
                        <th>Fecha</th>
                        <th>Cuadrilla</th>
                        <th>Aprobado por</th>
                        {% if es_coordinador %}
                        <th></th>
                        {% endif %}
                    </tr>

                    {% for parte in tarea.partedetrabajo_set.all %}

                        <tr>

                            <td><a href="{% url 'servicios:parte' parte.id %}">{{parte.descripcion}}</a></td>
                            <td>{{parte.fecha}}</td>
                            {% if parte.aprobado_por %}
                                <td><a href="{% url 'servicios:cuadrilla' parte.tarea.cuadrilla.id %}">{{parte.tarea.cuadrilla}}</a></td>
                                <td>{{parte.aprobado_por}}</td>
                            {% else %}
                                <td>No seleccionada</td>
                                <td>No aprobado</td>
                                {% if es_coordinador %}
                                    <td>
                                        <a class="btn btn-primary"
                                           href="{% url 'servicios:aprobar_parte' parte.id %}">Aprobar parte</a>
                                    </td>
                                {% endif %}
                            {% endif %}

                        </tr>

                    {% endfor %}
                </table>
            {% else %}
                <p>No hay partes de trabajo</p>
            {% endif %}

            {% if es_coordinador %}
                <p><a href="{% url 'servicios:nuevo_parte_coord' tarea.id %}"><button type="button" class="btn btn-primary">Agregar Parte</button></a></p>
            {% else %}
                <p><a href="{% url 'servicios:nuevo_parte' tarea.id %}"><button type="button" class="btn btn-primary">Agregar Parte</button></a></p>
            {% endif %}

        {% endfor %}

{% else %}
    <p>No hay tareas disponibles</p>
{% endif %}

{% endblock %}

proyecto/servicios/templates/servicios/tarea.html
{% extends 'servicios/base.html' %}

{% block main %}


<h3><b>Tarea</b>:</h3>

<div class="detail">
    <h5><b>Descripción:</b> {{ tarea.descripcion }}</h5>
    <h5><b>Servicio:</b> {{ tarea.servicio }}</h5>
    <h5><b>Estado:</b> {{ tarea.estado }}</h5>
    <h5><b>Cuadrilla Asignada:</b> {{ tarea.cuadrilla|default_if_none:"Sin Asignar"}}</h5>
</div>

{% if es_coordinador or es_administrativo %}
<p> 
    <a href="{% url 'servicios:editar_tarea' tarea.id %}"><button type="button" class="btn btn-primary">Editar Tarea</button></a>
    <a href="{% url 'servicios:eliminar_tarea' tarea.id %}"><button type="button" class="btn btn-primary">Eliminar Tarea</button></a>
    {% if tarea.estado != 'Finalizado' %}
        <a href="{% url 'servicios:finalizar_tarea' tarea.id %}"><button type="button" class="btn btn-primary">Finalizar Tarea</button></a>
    {% endif %}
    <a href="{% url 'servicios:detalle' tarea.servicio.id %}"><button type="button" class="btn btn-primary">Volver a Servicio</button></a>
</p>
{% endif %}

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

{% if tarea.partedetrabajo_set.all %}
    <h4>Partes de trabajo</h4>
    <table class="table">
            
        <tr>
            
            <th>Descripción</th>
            <th>Fecha</th>
            <th>Cuadrilla</th>
            <th>Aprobado por</th>
        </tr>
            
        {% for parte in tarea.partedetrabajo_set.all %}
            
            <tr>
                
                <td><a href="{% url 'servicios:parte' parte.id %}">{{parte.descripcion}}</a></td>
                <td>{{parte.fecha}}</td>
                <td><a href="{% url 'servicios:cuadrilla' parte.tarea.cuadrilla.id %}">{{parte.tarea.cuadrilla}}</a></td>

                {% if parte.aprobado_por %}
                    <td>{{parte.aprobado_por}}</td>
                {% else %}
                    <td>No aprobado</td>
                    {% if es_coordinador %}
                        <td>
                        <a class="btn btn-primary"
                           href="{% url 'servicios:aprobar_parte' parte.id %}">Aprobar parte</a>
                        </td>
                    {% endif %}
                {% endif %}
            </tr>
                
        {% endfor %}
    </table>
{% else %}
    <p>No hay partes de trabajo</p>
{% endif %}

{% if es_coordinador %}
    <p><a href="{% url 'servicios:nuevo_parte_coord' tarea.id %}"><button type="button" class="btn btn-primary">Agregar Parte</button></a></p>
{% else %}
    <p><a href="{% url 'servicios:nuevo_parte' tarea.id %}"><button type="button" class="btn btn-primary">Agregar Parte</button></a></p> 
{% endif %}            

{% endblock %}